### ISSUE TITLE
keyboard show on click 

### ISSUE THREAD

**Issue by setali** [mBut/jquery.mlkeyboard#5]
i have an image near the field. i want ml keyboard show when click on image, instead of open at focus, and hide at blur or click on image if keyboard was shown.
please help me.

**Comment by mBut** [comment]
Hi. I added custom trigger support. You can check how it works on demo page http://mbut.github.io/jquery.mlkeyboard/
If you would like to disable on focus behaviour then you can pass additional argument to options
`show_on_focus: false`
