### ISSUE TITLE
The first keyboard is not hidden when there are multiple input fields.

### ISSUE THREAD

**Issue by VapiSoft** [mBut/jquery.mlkeyboard#7]
I have two input fields.
I load the keyboard in the second input and then click on the backround - it closes.
I load the keyboard in the first input - I cannot close it at all.
I checked your demo and has almost the same problem but reversed.
The English keyboard can be closed.
The other languages cannot be closed at all.

**Comment by ghost** [comment]
I think the problem is on line 24 in src/keyboard.js

``` javascript
this.$current_input = $("input[type='text']").first();
```

because the keyboard is initialized with the first input node as current input so if there are multiple input nodes can be some issues.

I have found a solution passing the selector to Keyboard function but I don't know if it is the best. I have just pulled a request.

**Comment by VapiSoft** [comment]
First I want to thank you very much for a great plugin, and for replying so quick to my comment.
Second, what is the fixed lines, I want to add them to my code.
I did some changes, to your code to enable me to work with Hebrew and English keyboards.
This means that changing the keyboard to English (Shift), Enables me to work with upper-case and lower-case letters (Caps-Lock).
If you want I can send you the revised code.
Also, I tried to find if I can move the keyboard from the bottom of the screen (to below the text line, or above it if not enough space), but I could not see how.
Is it possible? where in the code?

**Comment by ghost** [comment]
No problem but the owner of this plugin is [mBut](https://github.com/mBut) not me :) You can find the changes in my version of jquery.mlkeyboard I've forked [here](https://github.com/worgock/jquery.mlkeyboard).

You have added very interesting features If I have understood correctly. The best way to go next is to fork the repo, made the changes so I can see and try your version of jquery.mlkeyboard.

**Comment by VapiSoft** [comment]
Thanks.
Of course it is yours and I only use it in my project (I work for a statup).
You did not say if you want my changes, but if you do, please send me your
email, so i can send them to you.
Thanks again (for the great job).

Shlomo;

Shlomo Aran
http://www.mobile-gap.com
054-7399-340

**Comment by VapiSoft** [comment]
I tested it.
It now works great.
Thanks.
