### ISSUE TITLE
Trigger calling a lot of times when i press the trigger

### ISSUE THREAD

**Issue by Eiglimar** [mBut/jquery.mlkeyboard#8]
Hello i put a trigger like your example:

$('input').mlKeyboard({
     layout: 'pt_PT',
     active_shift: true,
     trigger: '#trigger-teclado'
});

then when i click on trigger, my mlkeyboard fires 4 times, and is not hidden.

can u help me?

**Comment by ghost** [comment]
Hi Eiglimar,

maybe isn't right solution but you can try my fork for this repo that resolve this issue.

**Comment by Eiglimar** [comment]
Hey @worgock i appreciate you for reply , all right, i will fork your repo for other oportunities, because i already figure out my problem making a whole new keyboard from scratch with html5, css and jquery, but again,  I appreciate you for your help!
